services:
  app:
    image: msip
    volumes:
      - ../app:/app/app
    platform: linux/amd64
    # metrics port
    ports:
      - 8000:8000
    networks:
      - msip-network
      - dapr-network
      
